# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"

gem 'rspec'
gem 'capybara'
gem 'capybara-webkit'
gem 'capybara-screenshot'
gem 'selenium-webdriver'
gem 'httparty'
gem 'chromedriver-helper'